README.md

This commit updates the table of contents within the README, removes colons from a number of README headers, and adds MIPS to the list of supported architectures.

Updated README TOC and supported architectures

---

README.md

Updating MIPS -> MIPS32 in readme to remove any confusion

Specifically mention MIPS32

---

.github/build.sh
.github/workflows/ci.yml

Change ST component build to release

Gg st component build

---

.github/docker-images/amazonlinux/Dockerfile
.github/docker-images/ubi8/Dockerfile
.github/docker-images/ubuntu-16-x64/Dockerfile
CMakeLists.txt.awssdk

Update SDK version w/ fix for building sharedlibs

Update SDK version w/ fix for building sharedlibs

---

CHANGELOG.md
CMakeLists.txt
README.md
config-template.json
docs/COMPILATION.md
docs/PERMISSIONS.md
setup.sh
source/config/Config.cpp
source/config/Config.h
source/main.cpp
source/samples/pubsub/PubSubFeature.cpp
source/samples/pubsub/PubSubFeature.h
source/samples/pubsub/README.md
source/util/FileUtils.cpp
source/util/FileUtils.h
test/util/TestFileUtils.cpp

The sample pub sub feature shows customers how they might leverage the shared mqtt connection available in the Device Client to accomplish some set of business logic
The Pub/Sub Sample Feature
The MQTT pub/sub functionality was tested using the test IoT MQTT client 

The sample pub sub feature

---

.github/docker-images/amazonlinux/Dockerfile
.github/docker-images/ubi8/Dockerfile
.github/docker-images/ubuntu-16-x64/Dockerfile
CMakeLists.txt
CMakeLists.txt.awssdk
cmake-toolchain/Toolchain-aarch64.cmake
cmake-toolchain/Toolchain-armhf.cmake
cmake-toolchain/Toolchain-mips.cmake

- It is a good practice to set system architecture manually for cross compilation. This was missing so I have added the supporting code.
* Manually set desired system architecture for cross compilation.
* Updated the SDK commit id to use latest code from SDK.
* Updated Docker images with correct SDK flags
* Statically linked aws library.
* Linked OpenSSL and Crypto libraries. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Manually set desired system architecture for cross compilation.

---

README.md
source/shadow/README.md

fix a typo error and rephrase some words in shadow readme based on Shantanu's advice
update shadow readme toadd explanation on shadow current capabilities. 

update shadow readme toadd explanation on shadow current capabilities

---

README.md

fix some foramt issue in main readme

fix some foramt issue in main readme

---

setup.sh

- Issue number: https://github.com/awslabs/aws-iot-device-client/issues/178
Enabled SDK config in setup.sh to prompt customers

Enabled SDK logging through setup

---

source/main.cpp

- Not all AWS CRT SDK initialization failures are due to MQTT, but device client initialization reports any failure of AWS CRT SDK as MQTT failure.  
- Change the error message when calling `SharedCrtResourceManager::initialize` from main.cpp.  
- In the example output from [1] below, the reason for failure is due to incorrect directory permissions, but the device client reports an MQTT error.
- After applying the change on this PR, the reported message from [2] is made more generic and does not contradict the cause of failure in the `SharedCrtResourceManager::initialize`.
[1] existing behavior on main branch
```
2021-12-15T17:33:04.887Z [ERROR] {SharedCrtResourceManager.cpp}: Incorrect directory permissions for SDK log file: /tmp/aws-iot-device-client-clion/ expected: 745 received: 755 …
```

Improve error message from AWS CRT SDK initialization failure

---

.github/workflows/lint.yml
source/SharedCrtResourceManager.cpp
source/devicedefender/DeviceDefenderFeature.cpp
source/fleetprovisioning/FleetProvisioning.cpp
source/jobs/JobsFeature.cpp
source/main.cpp
source/samples/pubsub/PubSubFeature.cpp
source/sensor-publish/HeartbeatTask.cpp
source/sensor-publish/Sensor.cpp
source/tunneling/SecureTunnelingContext.cpp
source/tunneling/SecureTunnelingFeature.cpp
source/util/StringUtils.cpp

This reverts commit 330b23ebeb6fdcb020d043a95a07fcd21853ef4d.
Last commit broke the linter.
This reverts commit 330b23ebeb6fdcb020d043a95a07fcd21853ef4d.

Revert "Fixes formatting and lint workflow (#264)"

---

.github/docker-images/amazonlinux/Dockerfile
.github/docker-images/ubi8/Dockerfile
.github/docker-images/ubuntu-18-x64/Dockerfile

- Add softhsm2 in our docker builds so user does not have to deal with the issue of installing it manually. 

Add softhsm2 into our docker images.

---

setup.sh
source/config/Config.cpp
source/fleetprovisioning/FleetProvisioning.cpp
test/config/TestConfig.cpp

- Issue number: #301 
- We were creating directory files with incorrect file permissions. 
* Not to redundantly create default files with user has already created and passed file path. 
* Not to create file with incorrect permissions 
- Manually tested the changes.

Removed code which was redundantly creating  dir with incorrect permissions. 

---

source/util/Retry.h

Retry.h: fix include for gcc12

---

source/devicedefender/DeviceDefenderFeature.cpp
source/devicedefender/DeviceDefenderFeature.h
source/devicedefender/ReportTaskWrapper.cpp
source/devicedefender/ReportTaskWrapper.h
test/devicedefender/TestDeviceDefender.cpp
test/jobs/TestJobsFeature.cpp

Needed to make Device Defender more testable and allow mocking for further development.
Refactored DD for testability. Added additional unit tests.
unit tests

Device Defender Tests

---

source/SharedCrtResourceManager.h

Directives should not be included in header files: https://mariusbancila.ro/blog/2009/04/14/avoid-using-directives-in-header-files/
Remove directive from header file
unit tests

Remove directive from header file

---

test/devicedefender/TestDeviceDefender.cpp

Minor fix needed to remove warning.
unit tests

fix DD expect_call

---

CMakeLists.txt.versioning

check exit code of execute process

---

.github/docker-images/README.md
README.md

Removing the links to ECR repository. 

Removed ECR image links

---

.github/workflows/e2e-ci.yml

ci tests not pulling correct docker image due to version string being empty

Fix versioning output

---

sample-job-handlers/reboot.sh

Stop failing job if reboot doesn't block execution.
- Issue number: https://github.com/awslabs/aws-iot-device-client/issues/338
Manually tested.

Fix reboot handler

---

source/fleetprovisioning/FleetProvisioning.cpp
source/util/StringUtils.cpp
test/util/TestStringUtils.cpp

Reverts awslabs/aws-iot-device-client#371

Revert "Remove null terminator from formatted string"

---

source/jobs/JobEngine.cpp

- Issue number: https://github.com/awslabs/aws-iot-device-client/issues/378
Fixed uninitialized parameter.

Fix uninitialized parameter

---

CMakeLists.txt

- Cherry pick commit into branch
- Issue number: #326

fix: build flags for samples

---

source/fleetprovisioning/FleetProvisioning.cpp
source/util/StringUtils.cpp
test/util/TestStringUtils.cpp

change format function

---

source/main.cpp

* wrap lockfile invocation in ifdef

Patch for Greengrass Secure Tunneling failure to start (#391)

---

docs/SETUP.md

Updated readme documentation with correct information
Testing if integration tests are working fine or not.
N/A
N/A

Updated readme

---

source/config/Config.cpp

Removed HTTP proxy code for GG Secure Tunneling component
Tested changes locally. 

Removed HTTP proxy code for GG Secure Tunneling component

---

source/SharedCrtResourceManager.cpp

Added null check before closing connection
N/A
Manually tested 

Added null check before closing connection

---

docker-build.sh

- cherry picking https://github.com/macano953/aws-iot-device-client/commit/2c1af4ec3e7c4028fb1d6a63a77459aa26c9244a
- running CI workflow

Fix docker-build.sh

---

.github/workflows/sonarcloud.yml

Fix sonarcloud build failure
Updated sonarsource to v3 

update sonarsource github action to v3

---

.github/workflows/doxygen.yml

Fix doxygen deployment

---

.github/workflows/doxygen.yml
source/fleetprovisioning/FleetProvisioning.h

Update checkout options for doxygen

---

.github/docker-images/integration-tests/ubuntu/Dockerfile
.github/workflows/e2e-ci.yml

Remove integration test github secrets and add OIDC role based authentication for best security practices.

Remove integration test github secrets and add OIDC role based Auth for best security practices

---

.github/docker-images/integration-tests/ubuntu/Dockerfile

Update Local Proxy commit to resolve boost API update errors during execution of integration tests

Update Local Proxy commit to latest one to resolve boost API update errors

---

.github/workflows/e2e-ci.yml
.github/workflows/sonarcloud.yml

Fix sonarcloud
Specify gcov version during execution to prevent version ambiguity error

Fix sonarcloud

---

.github/workflows/e2e-ci.yml
integration-tests/source/IntegrationTestResourceHandler.cpp

Fixing lint CI check
Executed the clang script locally with no failures

Lint CI fix
