.github/docker-images/amazonlinux/Dockerfile, .github/docker-images/ubi8/Dockerfile
There was an issue with the existing Dockerfiles for OpenSSL installation. This commit addresses the issue by changing the instructions and eliminating a binary linking step.
=> Fix Ubi8 and Al2 Dockerfile Openssl install

setup.sh
Prior to this commit, our setup script did not properly encode colors for our prompts on various platforms. This is causes by variances in the default implementation of 'echo' in different shell types (such as Dash, Bash, etc.). To resolve this problem, I have converted the setup script from using echo to printf which is widely considered to be a better option for compatibility. I have tested on Ubuntu and RHEL instances and it appears that the script is now working as expected.
=> Address cross-platform compatibility for ANSI color codes

source/SharedCrtResourceManager.cpp, source/main.cpp
This commit addresses an issue where we may continue with feature startup even if we fail to build the MQTT client. The issue was caused by bubbling up the return code of an SDK function when we should just be returning the ABORT constant.
=> Add abort if MQTT client configuration fails

CHANGELOG.md, README.md, config-template.json, setup.sh, source/config/Config.cpp, source/config/Config.h, source/fleetprovisioning/FleetProvisioning.cpp, source/fleetprovisioning/FleetProvisioning.h, test/config/TestConfig.cpp
*Issue #101*
With this commit, I am adding config option for user to provide the device private key location via CLI or JSON file. This option will be required for provisioning the device using CSR file (CreateCertificateFromCsr API). If the device key or the CSR file is not provided, Device Client will use claim certificate and bootstrap private key (CreateKeysAndCertificate API) for provisioning the device.
=> Added support for new config option for taking device private key location

.github/build.sh, .github/workflows/ci.yml
Update armhf cross from MinSizeRel -> RELEASE
This solves the uninitialized warning from aws-c-http
=> Update armhf cross from MinSizeRel -> RELEASE

.github/workflows/ci.yml, setup/appspec.yml, setup/codedeploy/start_service.sh, setup/codedeploy/stop_service.sh
This commit adds support for including CodeDeploy configuration files in device client archives to enable automated deployment to our integration test machines.
=> Add CodeDeploy config for integration test setup

.github/build.sh, .github/workflows/ci.yml
Build was failing due to files being created in the build folder with different permissions.
=> Fix for build failing due to permissions.  Removing unnessary build files

README.md, source/SharedCrtResourceManager.cpp, source/SharedCrtResourceManager.h, source/tunneling/SecureTunnelingFeature.cpp
* Added Notice about charges incurred to Readme
* Moved aws_http_library_init to sharedCRTResourceManager
There is on reason to call aws_http_library_init if multiple features
require this especially when dealing with feature compilation.
It should be handled by the sharedCRTResourceManager where we can ignore
additional calls to initialize it.
=> Added notice about charges to README, moved aws_http_library_init to sharedCRTResourceManager

.github/workflows/ci.yml
This commit modifies the existing ci.yml file for our Github actions configuration to reduce the number of parent folders included in the generated archive. Prior to this commit, our files were being archived within build/ and setup/ folders. After this change, the binary and the appspec.yml file for CodeDeploy are placed directly in the root directory of the archive, with CodeDeploy specific files going in their own folder and shared libraries being given their own folder.
=> Modify GitHub Actions artifact archival to reduce folder hierarchy

setup/appspec.yml, setup/codedeploy/before_install.sh
This commit adds a before_install step to our CodeDeploy configuration to enable deletion of existing artifacts from the /sbin folder of our integration test machines. Our CodeDeploy deployments are currently failing without this change, since the artifact already exists when we attempt to deploy the new one.
=> Add artifact removal configuration for integration tests

.github/workflows/ci.yml
This commit adds a "static" suffix to the artifacts generated by our Github actions in order to allow our integration test infrastructure to appropriately differentiate between the static and shared artifacts types without having to do too much handling on the other end. Otherwise, our object key designators match to both the shared and static artifact implementations and trigger the wrong CodeDeploy deployments.
=> Add static suffix to artifact names

.github/workflows/ci.yml, .github/workflows/lint.yml
Added logic to run on pull_request and push, but to skip test instead of running double when not forked
Run actions on PR if forked, and skip if NOT forked
CI test run result: 
https://github.com/awslabs/aws-iot-device-client/actions/runs/746478459
https://github.com/awslabs/aws-iot-device-client/actions/runs/746459219
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> Added logic to run on pull_request and push

CHANGELOG.md, source/samples/pubsub/PubSubFeature.cpp
Problem identified by @matthewpaul 
We have a default payload, if a "data input file" isn't provided.  when the publish actions was "retriggered"  the lambda function would lose reference on the default allocator causing it to publish a blank string
This is solved by using our sharedCRT allocator instead of the default one
Tested with IoT MQTT Client
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> Resolved issue where pub sub sample lost reference on the Default Publish Payload allocator, publishing a blank string

config-template.json, source/config/Config.cpp
- With Pub-Sub sample disabled and config items with empty value in the pub-sub block, the DC application was failing to start with and segmentation fault. 
- ExportDefaultSetting method was not updated with our default config file provided to our customers. 
```
./aws-iot-device-client 
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```
- Updated LoadFromJson function for pub-sub sample to resolve segmentation fault 
- Updated ExportDefaultSetting to sync with our default 'config-template.json' file. Added configs for Logger and FP.
- Removed Error Logs from validation method to avoid confusion as …
=> Updated LoadFromJson function for pubsub sample to resolve seg fault

source/logging/StdOutLogger.cpp, source/logging/StdOutLogger.h
- We found the issue that it will take almost 99% of CPU when device client is running, this change is going to fix this by adding sleep time in an infinite while loop we use in StdoutLogger. 
- Issue number:  https://github.com/awslabs/aws-iot-device-client/issues/14
This a one-line change to make logger thread sleep 25ms after every time we fetch a log message from log queue
**Is your change tested? If not, please justify the reason.**  I've tested this change on my personal testing machines and I verified that CPU utilization would be down to 1% after I add sleep time
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> fix the high cpu utilization issue caused by infinite while loop in StdoutLogger

source/logging/FileLogger.cpp, source/logging/FileLogger.h
- We found the issue that it will take almost 99% of CPU when device client is running, I had made a change on StdLogger file but this change is going to fix this by adding sleep time in an infinite while loop we use in FileLogger
- Issue number: https://github.com/awslabs/aws-iot-device-client/issues/147
This a one-line change to make logger thread sleep 1ms after every time we fetch a log message from log queue
**Is your change tested? If not, please justify the reason. I've tested this change on my personal testing machines by running DC as service with FileLogger enabled and I verified that CPU utilization would be down to 1% after I add sleep time
**Please list your testing steps and …
=> Another fix of the high cpu utilization issue caused by infinite while loop in FileLogger

source/SharedCrtResourceManager.cpp, source/SharedCrtResourceManager.h
- This change is made to add support for logging connection calls coming from Device Client. Before this we were logging SDK calls only.
- Passed Device Client version and binary name to SDK to log calls coming from Device Client.
- CI test run result: 
=> Pass Device Client Telemetry data to SDK to log connection calls comming from Device Client

.github/docker-images/amazonlinux/Dockerfile, .github/docker-images/ubi8/Dockerfile, .github/docker-images/ubuntu-16-x64/Dockerfile
- Release builds require git submodules to be pinned to known versions.
- Dockerfile build will perform git submodule update before checking out release version. As a result, the release build might not use the intended version of submodule dependencies.  This results in broken builds or builds inadvertently compiled with an incompatible dependent version.
- Change the order in Dockerfile build so that we checkout release version before git submodule update.
N/A
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> Move git submodule update after checkout in docker build

source/config/Config.cpp
- We were not storing Job Handler Directory field from Jobs feature config file.
- Added support for fetching Job Handler directory field from config file
N/A
- Manually tested the change
=> Added support for fetching Job Handler directory field from config file

sample-job-handlers/restart-services.sh, sample-job-handlers/start-services.sh, sample-job-handlers/stop-services.sh, source/config/Config.cpp
- The `service_name` should appear before `command` in service job handlers, but are transposed.  As a result, the handler will always fail.
- Reorder so that `service_name` appears before `command` in service job handlers. 
N/A
=> Handler typo

source/jobs/JobEngine.cpp
- Added support to add '/' in the end for job handler directory path.
- Added support to add '/' in the end for job handler directory path.
* Manually tested
=> Added support handler directory paths ending with '/'

source/config/Config.cpp, source/config/Config.h, source/jobs/JobEngine.cpp, source/main.cpp, source/util/EnvUtils.cpp, source/util/EnvUtils.h, source/util/StringUtils.cpp, source/util/StringUtils.h, test/CMakeLists.txt, test/util/TestEnvUtils.cpp, test/util/TestStringUtils.cpp
* Managed job templates feature will look for job handlers in `./job` subdirectory of the default device client config directory and device client current working directory.
* On startup, add both the default device client config directory and the current working directory as well as standard subdirectories (`./job`) to the `PATH` environment variable.
* This is the value of PATH that is set and logged on startup when I run device client on my ubuntu 20 image.
```
/usr/local/sbin:
/usr/local/bin:
/usr/sbin:
/usr/bin:
/sbin:
/bin:
/root/.aws-iot-device-client:           << added to PATH by device client on startup 
/root/.aws-iot-device-client/jobs:      << added to PATH by device client on startup 
/tmp/aws-iot-device-client-clion:       << added to PATH by device client on startup …
```
=> Append subdirectories of device client current working directory to PATH

source/config/Config.cpp, source/util/FileUtils.cpp, test/util/TestFileUtils.cpp
- Issue number: #200 
The Device Client was failing with an segmentation fault if the value of job handler directory path passed via config file was empty. With this change I have added validation check for empty value of job handler directory path. 
- CI test.
- Manually tested the change. 
=> Added validation check for empty value of job handler directory path

docs/PERMISSIONS.md, setup.sh, source/config/Config.cpp, source/config/Config.h, source/samples/pubsub/PubSubFeature.cpp, source/samples/pubsub/PubSubFeature.h, source/util/FileUtils.cpp
- Added PubSub directory creation in setup.sh. Added PubSub Directory/files creation in pubsub.cpp
=> enabled dir creation in setup.sh and dir/file creation in pubsub.cpp

.github/workflows/ci.yml
- Doxygen CI test was spiking because of wrong condition.
Updated the condition to trigger doxygen update on merge event.
=> Updated github workflow to trigger doxygen update on merge event

CMakeLists.txt.awssdk, patches/aws-c-iot/0001-Fix-secure-tunneling-bug-sending-from-destination-to.patch
* Bug in aws-c-iot used by device client results in deadlock when sending files >= 15000 bytes from destination to source.
* Apply patch to commit `a73593d` of `aws-iot-device-sdk-cpp-v2` which pulls in the aws-c-iot as a git submdule.
- Customers reported issues sending large files using secure tunneling.
- Further investigation revealed that the device client secure tunneling thread will always deadlock when sending files >= 15000 bytes from destination to source.
- No issue for files of any size when sending from source to destination.
- The root cause of the deadlock is a bug in commit `118c5bf` of the secure tunneling library in `aws-c-iot`.
- The `aws-c-iot` library is a git submodule pulled in from commit `73593d` of aws-iot-device-sdk-cpp-v2. 
- This commit applies a patch which …
=> Patch secure tunneling bug in aws-c-iot

source/samples/pubsub/PubSubFeature.cpp, source/samples/pubsub/PubSubFeature.h
- if pubFile and subFile is empty, the MQTT will not publish default on the terminal
- Issue number: 211
=> Bug fix for pub sub creation

source/devicedefender/DeviceDefenderFeature.cpp
- Device Defender feature was subscribing & unsubscribing  to `/accepted` topic twice.
- Device Defender feature was not subscribing & unsubscribing to the `/rejected` topic. 
Updated Device Defender code to subscribe and unsubscribe to correct `/rejected` topic. 
Manually tested the code.
=> Updated DD code to subscribe to /rejected topic

source/jobs/JobsFeature.cpp, source/jobs/JobsFeature.h
Job Client should only retry JobExecutionStatusUpdates after a retryable error
This was causing delays in high latencies for job execution. 
- Makes only Throttled, ResourceNotFound, and InternalError errors retryable for UpdateJobExecutionStatus
- Adds Job ID to log output to help with debugging.
=> Adds retryable and non-retryable errors for UpdateJobExecutionStatus

source/jobs/README.md, source/shadow/README.md, source/tunneling/README.md
We were lacking an explanation of the necessary permissions to use secure tunneling.
Adds details about the required permissions to the ReadMe.
=> Adds Permissions info to ST ReadMe

sample-job-handlers/download-file.sh
The Job would fail when customers passed a directory for the destination of a Download File action. This change allows a directory to be used as the destination file.
The Download File handler will now check if the file passed as destination is a directory and if so will place the file in that directory.
Manually tested via the console.
=> Modifies Download-File handler

source/logging/Logger.cpp
https://sim.amazon.com/issues/DC-2727
switched timestamp to use UTC to be consistent with SDK timestamps
=> switch timestamp to UTC

source/logging/Logger.h, test/util/TestFileUtils.cpp
Some of our existing unit tests that are not valgrind clean.
This PR makes the tests valgrind clean (see before and after snippets pasted below) and fixes a real memory leak in FileLogger.
Before.
```
root@462ca6854276:/src/build-debug# valgrind --leak-check=yes ./test/test-aws-iot-device-client
...
==714==
==714== HEAP SUMMARY:
==714==     in use at exit: 2,360 bytes in 14 blocks
==714==   total heap usage: 5,100 allocs, 5,086 frees, 1,295,537 bytes allocated
...
==714== LEAK SUMMARY:
==714==    definitely lost: 632 bytes in 8 blocks
==714==    indirectly lost: 1,728 bytes in 6 blocks
==714==      possibly lost: 0 bytes in 0 blocks
==714==    still reachable: 0 bytes in 0 blocks
==714==         suppressed: 0 bytes in 0 blocks
==714==
==714== For lists of detected and suppressed errors, …
```
=> Fix a minor memory leak and make tests valgrind clean

source/main.cpp
- From cppreference, calling exit() allows for: "Objects with static storage duration are destroyed (C++) and functions registered with atexit are called."
- Replacing abort() with shutdown() is not possible because of segmentation fault of the resource manager if called before we attempt the mqtt connection.
- Performed a global search of the source code and no other calls to abort() were made.
- manually tested by calling deviceClientAbort at different places 
=> replace abort with exit

.github/build.sh, source/logging/LogQueue.cpp, source/logging/LogQueue.h, test/logging/TestLogQueue.cpp
- One of our unit tests has been failing due to a race condition bug in our logging code.
replaced wait() with wait_for(), which establishes a maximum duration for the thread to unblock itself if the condition variable never gets notified.
- tested via code tracing and lots of test runs, will need additional time to completely verify fix.
=> Fix logging race condition

source/util/FileUtils.h
- Issue number: https://github.com/awslabs/aws-iot-device-client/issues/186
In file `source/util/FileUtils.h` it uses `mode_t` in https://github.com/awslabs/aws-iot-device-client/blob/191c842e9c2a053ffa0be4e450cdf71cc36ccfbb/source/util/FileUtils.h#L118 without including necessary header and cause compile error in Musl-C toolchain. It can be fixed by including necessary header `sys/stat.h`.
I compiled it with Musl-C toolchain and verified it by running it on OpenWRT device with Musl-C runtime.
By submitting …
=> Fix compile error for Musl C

.github/build.sh, .github/docker-images/amazonlinux/Dockerfile, .github/docker-images/ubi8/Dockerfile, .github/docker-images/ubuntu-16-x64/Dockerfile, test/CMakeLists.txt, test/config/TestConfig.cpp
* Add memory leak detection when running unit tests using valgrind.
* Add valgrind to the base image.
* Run valgrind when running unit tests from build.sh.
* Add custom target named `test-aws-iot-device-client-leak-check` to cmake that runs the unit tests with valgrind in the same way as build.sh.
* Unit tests only.
=> Enable valgrind as part of build

source/config/Config.cpp, source/util/FileUtils.cpp, test/config/TestConfig.cpp
The GG ST Component passes a placeholder value for root-ca which was causing failures.
Use an empty string when root-ca path is invalid.
Manually tested by opening tunnels.
=> Root ca fix

.github/build.sh, .github/docker-images/ubuntu-16-x64/Dockerfile, .github/docker-images/ubuntu-18-x64/Dockerfile, .github/workflows/ci.yml, source/shadow/SampleShadowFeature.cpp, source/util/Retry.cpp, test/jobs/TestEphemeralPromise.cpp
- Build with gcc 11 fails when calling this_thread::sleep_for.
- Found when investigating the issue below.
- Issue number: #146 
Added missing headers to fix.
=> bump ubuntu version, fix build issues with gcc 11

source/config/Config.cpp, source/config/Config.h, source/util/StringUtils.cpp, test/util/TestStringUtils.cpp
Caps max logging message size to a certain value. However, we do log the entire config file on startup so that message will be truncated if the max buffer size is too small
Documentation about null terminated strings has already been done at an earlier time.
=> implemented max logging size

.github/workflows/lint.yml, source/SharedCrtResourceManager.cpp, source/devicedefender/DeviceDefenderFeature.cpp, source/fleetprovisioning/FleetProvisioning.cpp, source/jobs/JobsFeature.cpp, source/main.cpp, source/samples/pubsub/PubSubFeature.cpp, source/sensor-publish/HeartbeatTask.cpp, source/sensor-publish/Sensor.cpp, source/tunneling/SecureTunnelingContext.cpp, source/tunneling/SecureTunnelingFeature.cpp, source/util/StringUtils.cpp
clang-format check was giving false positive format errors.
Changed workflow to use the format-check script. Formatted all files that were throwing format errors.
=> Fixes formatting and lint workflow

docs/CONFIG.md, source/config/Config.h, source/jobs/README.md, source/tunneling/README.md, test/config/TestConfig.cpp
Disabling Device Defender by default so that customers are not surprised by this feature being enabled without explicitly enabling it.
Make DD default disabled. Update Config tests to assert DD is disabled with minimum config. Add to documentation.
Unit tests
=> Disable device defender by default

source/config/Config.cpp, source/jobs/IotJobsClientWrapper.cpp, source/jobs/IotJobsClientWrapper.h, source/jobs/JobsFeature.cpp, source/jobs/JobsFeature.h, source/main.cpp, test/jobs/TestJobsFeature.cpp
Motivation
JobsFeature did not have unit tests. Some refactoring was required for testability.
Modifications
Change summary
Created an interface and wrapper for IotJobsClient so it could be mocked for testing JobsFeature.
Refactored jobs by splitting off methods which create new threads for mocking. Added a method to allow injecting a mock IotJobsClient.
Added unit tests.
Revision diff summary
Testing
Unit tests pass and ran Jobs feature locally.
=> Refactor Jobs and add unit tests

.github/docker-images/amazonlinux/Dockerfile, .github/docker-images/ubi8/Dockerfile, .github/docker-images/ubuntu-18-x64/Dockerfile, CMakeLists.txt.awssdk
* Fix segmentation fault when closing secure tunnel with null websocket
* Bump SDK to pick up secure tunnel fix in aws-c-iot [b50828c](https://github.com/awslabs/aws-c-iot/commit/b50828cf19821a7c21f3b8b4df352529b3fc0c39)
* Users who enable secure tunneling and shutdown the device client before the websocket connection is established would observe a segmentation fault.  That behavior is fixed as part of this commit.
=> Update SDK with secure tunneling null websocket fix

.github/build.sh, cmake-toolchain/Toolchain-mips.cmake
#116 
- Still have not completely root caused the issue, but seems like the S2N_NO_PQ flag does not get set even when explicitly defined in the cmake toolchain file.
manually set -DS2N_NO_PQ variable during call to cmake
- passed workflow
=> Fix for cross compile issue

source/config/Config.cpp, source/config/Config.h, source/main.cpp
CLI Arg parsing errors were returning 0, this fixes that by separating the help/version arg checks to a different method
```
dev-dsk-shangabl-2b-cfbafac5 % ./aws-iot-device-client --foo
2022-07-07T20:07:26.651Z [ERROR] {Config.cpp}: *** AWS IOT DEVICE CLIENT FATAL ERROR: Unrecognised command line argument: --foo ***
(22-07-07 20:07:26) <1> [/tmp/deviceclient/cmake-build-debug]  
dev-dsk-shangabl-2b-cfbafac5 % echo $?
1
```
=> Fixes CLI parsing bug

.github/docker-images/ubuntu-18-x64/Dockerfile, .github/workflows/lint.yml
Our CI build uses clang-format lint check provided by third party. The behavior of clang-format changes from version to version. When clang-format lint check fails, then we have to install the same version locally as the version used by the third party. Instead it would be easier if we install clang-format in one of our CI images so that we can reproduce clang-format failures locally.
Use clang-format installed on the `ghcr.io/awslabs/aws-iot-device-client/ubuntu-18-x64:latest` image.
Tested by CI build.
=> Replace third party clang format action with clang-format from ci image

source/jobs/JobEngine.cpp, test/jobs/TestJobEngine.cpp
- Issue number: #282 
Device Client's Jobs feature is coded in a way that to execute the job Execution, the argument list passed to `execv` command is in the following order:
```
argv[0] executable path
argv[1] Linux user name
argv[2:] arguments required for executing the executable file..
```
If `runAsUser` value is not passed or is empty string, DC will pass it as empty string to `execv`  because it is considered as a separate argument by shell script. In bellow example, we passed empty string for `runAsUser`   argument which is passed as empty string to the install-packages.sh script and is handled properly by the Job Handler. 
```
2022-07-15T19:29:38.848Z [DEBUG] {13126}: Running install-packages.sh …
```
=> Rolling back failing changes made for runAsUser.

CMakeLists.txt, test/CMakeLists.txt
The changes for the [http proxy](https://github.com/awslabs/aws-iot-device-client/commit/e19af866fa02d1651eb3debb7e7348fb95d0fde7) contains an unexpected change that adding ProxyUtil related class into the CMakeLists.txt. Since they're already included by the definition. Those lines are not needed. 
I think it's the one of the Clion formatter triggering that.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=>  Remove ProxyUtils related class from CMakeLists

.github/build.sh, test/config/TestConfig.cpp
- Exclude sensor publish feature when building device client binary exclusively for secure tunnel eg `st_component_mode`.
- When `EXCLUDE_SENSOR_PUBLISH=ON` then disable sensor publish configuration validation checks in unit tests.
- Unit tests.
=> Disable sensor publish feature for secure tunnel builds

docs/PERMISSIONS.md, source/config/Config.cpp, source/config/Config.h, source/fleetprovisioning/FleetProvisioning.cpp
- Issue number: #301 
- The required file permissions on the config files were incorrect and were strictly required.
I have updated the code with correct and more restrictive file permissions along with that I have also resolved one bug where we were failing to parse fleet provisioning runtime config file. 
- Manually tested the change. Steps to test the change can be found in the issue link provided above. 
By submitting this pull request, I confirm that you can use, modify, …
=> updated config file permissions

.gitignore, docs/README.md
Noticed that gitignore and readme both referenced doc folder, when it's actually docs.
Fix gitignore and readme to use docs instead of doc
Minimally tested. No change to code files.
Follow readme
cd docs
docygen
generated files don't show up in git changes.
=> Ignore correct docs folder, and update readme.

source/SharedCrtResourceManager.cpp
- In SharedCrtResourceManager class, we were calling same promise variable more than one time while closing MQTT connection. 
- Updated the logic to initialize new promise variable every time connection is established.  
- Tested manually. 
=> resolved error caused by calling same promise variable more than one time

test/CMakeLists.txt, test/devicedefender/TestDeviceDefender.cpp
Adding basic unit tests to device defender so there are some to work from for another project.
Unit tests
=> Add basic device defender unit tests

source/FeatureRegistry.cpp, source/FeatureRegistry.h, source/SharedCrtResourceManager.cpp, source/SharedCrtResourceManager.h, source/devicedefender/DeviceDefenderFeature.cpp, source/devicedefender/DeviceDefenderFeature.h, source/jobs/JobsFeature.cpp, source/jobs/JobsFeature.h, source/main.cpp, source/samples/pubsub/PubSubFeature.cpp, source/samples/pubsub/PubSubFeature.h, source/sensor-publish/SensorPublishFeature.cpp, source/sensor-publish/SensorPublishFeature.h, source/shadow/SampleShadowFeature.cpp, source/shadow/SampleShadowFeature.h, source/tunneling/SecureTunnelingFeature.cpp, source/tunneling/SecureTunnelingFeature.h, test/util/TestFeatureRegistry.cpp
Currently, main.cpp is using a vector to keep track of its active features. This is a very cumbersome solution. We introduce a new class, FeatureRegistry, which will behave exactly the same, but will abstract away some of the logic into its methods.
- Added FeatureRegistry.h/.cpp
- Added TestFeatureRegistry.cpp
- Modified Main.cpp to make use of this new class
- Modified SharedCrtResourceManager to make use of this class as well
Small Unit tests have been created to test basic functionality
ConfigShadow Feature currently has an error when enabled, the DC will not shut down gracefully.
=> Adanfo feature registry

source/fleetprovisioning/README.md
FP Documentation is incorrect. The provided example Claim Certificate Policy is incorrect and doesn't work. Tested manually, tested using the provided example here https://docs.aws.amazon.com/iot/latest/developerguide/provision-wo-cert.html which was successful.
Manually provisioned device using containers.
=> Fix Fleet Provisioning Documentation

source/fleetprovisioning/FleetProvisioning.cpp
The runtime config file created in device client's fleet provisioning feature was incorrect. Updated the file permission from `644` to `640`
=> Updated runtime config file permission

.github/docker-images/README.md, README.md
Removed the links to ECR docker images.
=> Removed ECR image links (#348)

.github/docker-images/Dockerfile, .github/docker-images/README.md, .github/docker-images/base-images/amazonlinux/Dockerfile, .github/docker-images/base-images/ubi8/Dockerfile, .github/docker-images/base-images/ubuntu/Dockerfile, .github/docker-images/integration-tests/centOS/Dockerfile, .github/docker-images/integration-tests/ubuntu/Dockerfile, .github/docker-images/oss-compliance/build-from-source-packages/build-from-source-package-licenses-ubi8.txt, .github/docker-images/oss-compliance/build-from-source-packages/build-from-source-package-licenses.txt, .github/docker-images/oss-compliance/generate-oss-compliance.sh, .github/docker-images/oss-compliance/linux-packages/dkpg-packages.sh, .github/docker-images/oss-compliance/linux-packages/yum-packages.sh, .github/docker-images/oss-compliance/test/test-oss-compliance.sh, README.md
Need to add oss compliance scripts which add attributions for open-source software.
Includes a test script to check that files were generated.
=> Add oss-compliance scripts for docker images

integration-tests/entry-point.sh, source/config/Config.cpp, source/main.cpp, source/util/LockFile.cpp, source/util/LockFile.h, test/util/TestLockFile.cpp
- Changes lockfile behavior in accordance to usability needs.
- now writes thing name to lockfile
=> Update lockfile handler

source/samples/pubsub/PubSubFeature.cpp, source/shadow/SampleShadowFeature.cpp
- While not intended to alter the feature behavior fundamentally, removes updating the desired state upon startup.
- Issue number: #358
Deletes the line that sets desired state to the Json object.
=> shadow fix and plug pubsub memory leak

.github/docker-images/integration-tests/ubuntu/Dockerfile
- Secure Tunneling Local Proxy Requires boost 1.79 now. Needed for integration tests.
Upgraded boost in the integration test docker images.
=> Upgrade boost to 1.79 for ST tests

.github/workflows/release-ci.yml, integration-tests/CMakeLists.txt, integration-tests/entry-point.sh, integration-tests/source/IntegrationTestResourceHandler.cpp, integration-tests/source/IntegrationTestResourceHandler.h, integration-tests/source/devicedefender/DeviceDefenderIntegrationTests.cpp, integration-tests/source/fleetprovisioning/FleetProvisioningIntegrationTests.cpp, integration-tests/source/jobs/JobsIntegrationTests.cpp, integration-tests/source/tunneling/SecureTunnelingIntegrationTests.cpp
- Need integration tests for Device Defender
Added Integration tests for DD
Fixed typo in ubi8 docker image tag
Added a Download File integration test for Jobs
=> Add Device Defender Integration Tests

source/config/Config.cpp, test/config/TestConfig.cpp
Stop loading json config parameters if feature is not enabled
Check if the feature is enable before loading the rest of the json config fields
=> Stop loading json config parameters if feature is not enabled

source/fleetprovisioning/FleetProvisioning.cpp, source/util/StringUtils.cpp, test/util/TestStringUtils.cpp
- Exporting the runtime config during fleet provisioning adds the null terminator character from the string format function, which shows up as ^@ in the file.
- changes remove this character from the string returned by FormatMessage()
=> Remove null terminator from formatted string

integration-tests/source/jobs/JobsIntegrationTests.cpp, sample-job-handlers/restart-services.sh
Fixing the infinite restart loop for Device Client when the managed template is used to restart the service.
- Issue number: https://github.com/awslabs/aws-iot-device-client/issues/365
Added integration test, added lock file to handler script.
Added integration test to handle the reboot case.
=> Fix infinite restart loop for Device Client

source/main.cpp, source/util/LockFile.cpp
- Moving the call to lockfile handler to indef, so it works with greengrass securetunneling component and does not enforce single process when MQTT is disabled.
=> Patch for Greengrass Secure Tunneling failure to start

.github/docker-images/base-images/amazonlinux/Dockerfile, .github/docker-images/base-images/ubi8/Dockerfile, .github/docker-images/base-images/ubuntu/Dockerfile, .github/docker-images/oss-compliance/build-from-source-packages/build-from-source-package-licenses-ubi8.txt, .github/docker-images/oss-compliance/build-from-source-packages/build-from-source-package-licenses.txt
Need to upgrade to CMAKE 3.13 due to some build issues with the integration tests resulting from OS updates
Updated attribution doc and Cmake version
=> Upgrade to CMAKE 3.13

source/config/Config.cpp, test/config/TestConfig.cpp
Apart from Secure Tunneling feature excluded all other feature validation and file creation when `DISABLE_MQTT` flag is enabled.
When `DISABLE_MQTT` is enabled, only ST feature is built in the binary so it does not make sense to read other feature config and validate it. 
N/A
Manually tested build
=> Excluded feature validation and file creation if DISABLE_MQTT flag is enabled.

CMakeLists.txt.versioning
DC artifact was failing to print DC version
Marked DC directory as safe to call git commands
Tested manually
=> Marking DC directory safe

source/main.cpp
* We were not closing resource manager MQTT connection before aborting. This was causing terminal getting stuck when `exit(1)` is called. 
* We did not have enough logs to help customer troubleshoot the issue. 
Minor Fix in DC abort logic and added more logs for debugging purpose
Manually tested changes locally
=> Minor Fix in DC abort logic and added more logs for debugging purpose

source/main.cpp
- Issue number: #418 
Device Client uses a lock files for making sure only 1 instance of Device Client is running at a given time. With Fleet Provisioning feature enabled, DC was accidentally creating multiple lock files which was resulting in DC abort. By updating the logic, DC will now only create one lock file as expected.
=> Removed DC initialization code which creates multiple lock files.

.github/docker-images/Dockerfile
- The device client binary we publish to public ecr is using a `Debug` build which results in a binary size of 32M in comparison to the `Release` build which produces a binary of 6M. 
Modify the release type of the device client builds used in Dockerfile from `Debug` to `Relase`
32M binary compiled using `Debug` — `cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . --target aws-iot-device-client`
```
root@6a67a591380f:/src/build-release# ls -lh aws-iot-device-client 
-rwxr-xr-x 1 root root 32M Aug  2 01:08 aws-iot-device-client
root@6a67a591380f:/src/build-release# ./aws-iot-device-client --version
v1.8.27-a0d1cf4
```
6M binary compiled using `Release` — …
=> Compile device client binaries as Release build type

.github/docker-images/integration-tests/ubuntu/Dockerfile, source/main.cpp, source/tunneling/SecureTunnelingFeature.cpp
- Greengrass Secure Tunneling component which use Device Client code was not closing the thread on getting the tunnel close notification.
- Updated code to shutdown Device Client on tunnel close callback
- Locally tested the changes does not affect the device client application logic
=> Updated code to shutdown on tunnel close callback

source/main.cpp, source/tunneling/SecureTunnelingFeature.cpp
- Secure tunneling component was failing to clean up the threads opened for each new tunnel. To resolve the issue, we are closing Device Client with `SIGTERM` signal. This will make sure that on tunnel close signal, we will send process termination signal which will eventually close all threads and free up all memory to avoid memory leak.
- Calling signal termination from tunnel close callback 
- Updated abort function to pass in exit code. 
- Tested locally by creating private component. 
=> Updated Secure Tunneling close logic for Secure Tunneling Component

source/main.cpp
fixed bug to read `SIGTERM` signal when sent form kernel
Manually tested changes
=> Fixed bug to read SIGTERM signal when sent form kernel

.github/docker-images/base-images/device-client/amazonlinux/Dockerfile, .github/docker-images/base-images/device-client/ubi8/Dockerfile, .github/docker-images/base-images/device-client/ubuntu/Dockerfile, .github/docker-images/oss-compliance/build-from-source-packages/build-from-source-package-licenses-ubi8.txt, .github/docker-images/oss-compliance/build-from-source-packages/build-from-source-package-licenses.txt, CMakeLists.txt.gtest, integration-tests/CMakeLists.txt.gtest
- Issue number: #428 
- With newer version of `gcc` lib used on Ubuntu 22, device client is failing to download and use google-test lib. We use google-test for unit testing. This issue was resolved by google-test developers in the latest version of the library. Updating the google-test lib version used in Device Client to resolve this build failure issue. 
- Updated google-test lib version to v1.12.0
N/A
- Manually tested on Ubuntu 22
- Tested changes on CI build
=> Updated google-test lib version to v1.12.0

source/config/Config.cpp
- Jobs and Secure Tunneling feature in Device Client are enabled by default. Added code for disabling jobs and secure tunneling feature if the features are not compiled in the binary. 
Disabled jobs and secure tunneling if they are not compiled into binary
N/A
* Manually tested on an Ubuntu 20 system. 
=> Disabled jobs and secure tunneling if they are not compiled into binary

source/util/MqttUtils.cpp, source/util/MqttUtils.h, test/config/TestConfig.cpp, test/util/TestMqttUtils.cpp
- Number of slash is not consistent in different topics and reserved topics.
- The rule applied for basic ingestion for number of slash is different from other reserved topics. 
- We have more validation tests added on the cloud side so we do not have to test this on client side.
- Removed the MQTT topic validation for number of slashes.
- Remove unit tests added for testing the slash limit in the MQTT topic.
N/A
- Manually tested changes locally. 
=> Removed number of slash validation for MQTT topics

.github/docker-images/base-images/device-client/amazonlinux/Dockerfile, .github/docker-images/base-images/device-client/ubi8/Dockerfile, .github/docker-images/base-images/device-client/ubuntu/Dockerfile, .github/docker-images/base-images/integration-tests/amazonlinux/Dockerfile, .github/docker-images/base-images/integration-tests/ubi8/Dockerfile, .github/docker-images/base-images/integration-tests/ubuntu/Dockerfile, .github/docker-images/integration-tests/amazonlinux/Dockerfile, .github/docker-images/integration-tests/ubi8/Dockerfile, .github/docker-images/integration-tests/ubuntu/Dockerfile, integration-tests/CMakeLists.txt, integration-tests/CMakeLists.txt.gtest, integration-tests/CMakeLists.txt.libawscpp
- Updated the OpenSSL version and added dependent lib
=> Updated the OpenSSL version and added dependent lib

source/config/Config.cpp
- Include http proxy for secure tunneling when aws-iot-device-client is built in st_component_mode
- Issue number: #449 
Http proxy configuration is loaded even if DISABLE_MQTT is defined. This allow for secure tunneling (aws-iot-device-client in st_component_mode) to work with a proxy.
- Tested by building the aws-iot-device-client in st_component_mode, with a proxy. I was able to established secure tunneling connection from AWS IoT Console.
=> Fixed for ST_COMPONENT_MODE with a proxy

source/config/Config.cpp, source/config/Config.h, source/fleetprovisioning/FleetProvisioning.cpp, source/fleetprovisioning/FleetProvisioning.h
- Issue number: #451
- added cli/json parsing to fleet provisioning collect system info flag
=> Add cli/json parsing to fleet provisioning collect system info flag

source/jobs/JobEngine.cpp
- The compilation phase on MacOS treats usage of vfork as an error instead of a warning. This changes vfork -> fork to allow compilation on MacOS.
-  
Just one change of vfork -> fork
No CI for this but I needed to make this change in order to build the project on Mac OS. fork does work slightly differently than vfork though so I may add some more comments later once I've verified that it works as expected.
=> Switch to fork from vfork

CMakeLists.txt
I am trying to build the aws-iot-device-client with BUILD_SDK=OFF and where the CMake build directory is not placed directly under the aws-iot-device-client. The build failed, reporting (for the googletest case):
```
CMake Error at aws-iot-device-client/CMakeLists.txt:264 (add_subdirectory):
add_subdirectory given source "/home/x/test/build/googletest-src" which
is not an existing directory.
```
The motivation for having the build directory in a non-standard location is to build aws-iot-device-client against a seperate checkout of the SDK along with other software that uses the SDK as part of a larger cross-compile build.
The solution is to add ${CMAKE_BINARY_DIR} to the output argument of the configure_file CMake function. With this, the CMakeLists.txt.gtest or CMakeLists.txt.awssdk file …
=> Fix configure_file output path by adding CMAKE_BINARY_DIR

source/fleetprovisioning/FleetProvisioning.cpp, source/fleetprovisioning/FleetProvisioning.h
- create a static filepath that gets overwritten upon a successful retry of the Fleet provisioning workflow.
- QoL for specific applications on the device that may need the x509 certificate to reside at a guaranteed location.
- extracted logic into a private function for calling it twice. First time with certificate ID and second time with the "active" prefix
- manually tested /w FP template
=> write provisioned certificate to "active-certificate.pem.crt"

source/config/Config.cpp
- Issue number: https://github.com/awslabs/aws-iot-device-client/issues/452
Modified condition to create default sample shadow directory only when the sample shadow feature is enabled and added corresponding logs
Tested the changes locally on my linux instance
=> Modified condition to create default sample shadow directory

.github/workflows/e2e-ci.yml, .github/workflows/release-ci.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> ci: Use GITHUB_OUTPUT envvar instead of set-output command

source/fleetprovisioning/FleetProvisioning.cpp, source/fleetprovisioning/FleetProvisioning.h, source/jobs/JobsFeature.cpp, source/jobs/JobsFeature.h
Fix formatting wrt clang format
=> Fix formatting wrt clang format

README.md, docs/Doxyfile
=> Use readme.md as main page for Doxygen

CMakeLists.txt.versioning
- Please give a brief description for the background of this change:
This PR updates the patch versioning by counting the number of commits that happened from the last major minor version tag as the patch number instead of counting from the last patch release so that the patch version number will always be incremental. 
=> Fix patch versioning to count the number of commits from last major minor

.github/docker-images/base-images/device-client/amazonlinux/Dockerfile, .github/docker-images/base-images/device-client/ubi8/Dockerfile, .github/docker-images/base-images/device-client/ubuntu/Dockerfile, .github/docker-images/base-images/integration-tests/amazonlinux/Dockerfile, .github/docker-images/base-images/integration-tests/ubuntu/Dockerfile, .github/workflows/base-images.yml, .github/workflows/e2e-ci.yml, .github/workflows/release-ci.yml
- fixing broken docker images builds
- removing ubuntu armv7 build
- update Dockerfile args in the workflow definitions
=> fix docker base image builds

.github/workflows/coverity.yml
In order to alleviate potential security risks, we need to migrate to short-term temporary credentials instead of long-term access keys. Hence we plan to move to Github OIDC to achieve this requirement.
- Removed Github secrets that were being used for authentication with AWS.
- Updated configure-aws-credentials to v2 which is the recommended version for OIDC support.
=> Remove Github secrets and migrate to Github OIDC for AWS Authentication

.github/workflows/base-images.yml, .github/workflows/build.yml, .github/workflows/coverity.yml, .github/workflows/cppcheck.yml, .github/workflows/e2e-ci.yml, .github/workflows/lint.yml, .github/workflows/release-ci.yml
Replacing Github secrets and migrating to Github OIDC for AWS Authentication as a measure of better security practices in all workflows.
Using Identity Provider and IAM role based authentication for AWS access
=> Migrate from Github Secrets to GitHub OIDC

.github/docker-images/integration-tests/ubuntu/Dockerfile, .github/workflows/e2e-ci.yml, integration-tests/source/IntegrationTestResourceHandler.cpp
Fix Integration Tests segmentation fault error
Tested changes locally
=> Fix integration tests segmentation fault error

.github/workflows/e2e-ci.yml
Injected the AWS credentials we get by using OIDC credentials into Integration Tests Docker Container to fix missing authentication token issue in workflow
=> Inject OIDC credentials into Integration Tests Container

.github/workflows/build.yml, .github/workflows/e2e-ci.yml
Fix versioning of information for every new Tagged release commit that we create.
Updated Build CI logic to trigger and upload artifacts upon Tag creations as well
=> Trigger Build CI on Tag push
